apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insider-app.fullname" . }}-config
  labels:
    {{- include "insider-app.labels" . | nindent 4 }}
data:
  # values.yaml'daki port numarasını buraya bağladık
  APP_PORT: {{ .Values.appConfig.port | quote }}