apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "insider-app.fullname" . }}-alerts
  labels:
    {{- include "insider-app.labels" . | nindent 4 }}
    release: prometheus
spec:
  groups:
  - name: insider-app.rules
    rules:
    - alert: FastAPIHighErrorRate
      expr: sum(rate(http_requests_total{status_code=~"5.*"}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Uygulamada HTTP Hata Oranı Çok Yüksek!"
        description: {{ printf "Pod {{ $labels.pod }} son 5 dakikada %%5'ten fazla HTTP 5xx hatası döndürüyor. Güncel oran: {{ $value }}%%" | quote }}