apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: insider-app-monitor
  namespace: insider-app
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: insider-app
  namespaceSelector:
    matchNames:
      - insider-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s