# Geliştirme (Test) ortamı konfigürasyonu
environment: "development"

replicaCount: 1

image:
  repository: insider-app
  tag: local
  pullPolicy: Never

service:
  type: NodePort
  port: 8080        # Container'ın içeride (FastAPI) dinlediği port
  nodePort: 30080   # Terraform Security Group'ta dünyaya açtığımız sabit port

# 2.3 Resources: Test ortamı için hafif kaynak sınırları
resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

# 2.5 Production-Ready Autoscaling Configuration Bonus 
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3      
  targetCPU: 70       