# Canlı (Production) ortamı konfigürasyonu
environment: "production"

# 2.2 High Availability: Prod ortamında 3 pod çalıştırarak kesintisiz hizmet sağlıyoruz!
replicaCount: 3

# 🚀 Canlı ortam imaj politikası 
image:
  repository: emretaskend/insider-app 
  tag: latest # CI/CD komutu bunu dinamik olarak değiştirecek (Örn: v1.0.0 veya commit_sha)
  pullPolicy: Always

# 2.3 Resources: Ani trafik yüklerini göğüslemek için kaynak sınırlarını dikeyde 2 katına çıkardık
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# 2.5 Production-Ready Autoscaling Configuration Bonus 
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10      # Canlı ortamda yüksek erişilebilirlik (HA) için en az 2 pod ile başlanır
  targetCPU: 70       # Prod ortamında yük durumuna göre 10 poda kadar çıkabilir