environment: "production"

replicaCount: 3

image:
  repository: emretaskend/insider-app 
  tag: latest 
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30080   # 🚨 EKLENDİ: EC2 iptables yönlendirmesi için şart!

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 3      
  maxReplicas: 5      # 🚨 DÜZELTİLDİ: t3.small CPU kapasitesini aşmamak için 5 ile sınırlandırıldı
  targetCPU: 75

serviceMonitor:
  enabled: true
  labels:
    release: prometheus-stack
  interval: 15s
  path: /metrics
  port: http