name: "Continuous Integration & DevSecOps Pipeline"

on:
  push:
    branches: [ "main", "feat/cicd-pipeline" ] # 🌟 TEST İÇİN GEÇİCİ OLARAK BİZİM BRANCH'İ DE EKLEDİM KANKA!
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write      
  contents: read       
  packages: write      

jobs:
  security-and-quality:
    name: "Code Quality & Security Scan"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Python Actions resmi topluluk standardı
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Lint with Ruff"
        run: |
          pip install ruff
          ruff check app/

      - name: "Check for Secrets with GitLeaks"
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}